"""add departments table

Revision ID: 25753b260180
Revises: 800c7f8c34e6
Create Date: 2025-12-07 15:45:10.178395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25753b260180'
down_revision: Union[str, None] = '800c7f8c34e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父部门ID,NULL表示顶级部门'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='部门名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='部门编码'),
    sa.Column('leader_id', sa.BigInteger(), nullable=True, comment='部门负责人ID'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False, comment='排序(升序)'),
    sa.Column('status', sa.Integer(), server_default='1', nullable=False, comment='状态:0禁用,1启用'),
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除人ID'),
    sa.Column('tenant_id', sa.BigInteger(), server_default='0', nullable=False, comment='租户ID,0表示平台级'),
    sa.PrimaryKeyConstraint('id'),
    comment='部门表'
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=False)
    op.create_index(op.f('ix_departments_parent_id'), 'departments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_departments_tenant_id'), 'departments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_tenant_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_parent_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
