"""add role custom_dept_ids and relationship

Revision ID: 4ca356db0472
Revises: 25753b260180
Create Date: 2025-12-07 17:12:47.572221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca356db0472'
down_revision: Union[str, None] = '25753b260180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_departments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('department_id', sa.BigInteger(), nullable=False, comment='部门ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'department_id', name='uk_role_department'),
    comment='角色部门关联表(自定义数据权限)'
    )
    op.create_index(op.f('ix_role_departments_department_id'), 'role_departments', ['department_id'], unique=False)
    op.create_index(op.f('ix_role_departments_role_id'), 'role_departments', ['role_id'], unique=False)
    op.alter_column('permissions', 'tenant_id',
               existing_type=sa.BIGINT(),
               comment='租户ID,0表示平台级',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_permissions_tenant_id'), 'permissions', ['tenant_id'], unique=False)
    op.alter_column('roles', 'data_scope',
               existing_type=sa.SMALLINT(),
               comment='数据权限:1全部,2本部门及以下,3本部门,4仅本人,5自定义',
               existing_comment='数据权限:1全部,2本部门及以下,3本部门,4仅本人',
               existing_nullable=False,
               existing_server_default=sa.text("'1'::smallint"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'data_scope',
               existing_type=sa.SMALLINT(),
               comment='数据权限:1全部,2本部门及以下,3本部门,4仅本人',
               existing_comment='数据权限:1全部,2本部门及以下,3本部门,4仅本人,5自定义',
               existing_nullable=False,
               existing_server_default=sa.text("'1'::smallint"))
    op.drop_index(op.f('ix_permissions_tenant_id'), table_name='permissions')
    op.alter_column('permissions', 'tenant_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='租户ID,0表示平台级',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_role_departments_role_id'), table_name='role_departments')
    op.drop_index(op.f('ix_role_departments_department_id'), table_name='role_departments')
    op.drop_table('role_departments')
    # ### end Alembic commands ###
