"""add_auth_models

Revision ID: 51079b45a694
Revises: 0ac5856111ee
Create Date: 2025-12-07 14:32:04.348773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51079b45a694'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('parent_id', sa.BigInteger(), server_default='0', nullable=False, comment='父级ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='菜单名称'),
    sa.Column('code', sa.String(length=100), nullable=True, comment='权限标识'),
    sa.Column('type', sa.SmallInteger(), server_default='1', nullable=False, comment='类型:1目录,2菜单,3按钮'),
    sa.Column('path', sa.String(length=255), nullable=True, comment='路由路径'),
    sa.Column('component', sa.String(length=255), nullable=True, comment='前端组件'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='图标'),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False, comment='排序'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='状态:0禁用,1正常'),
    sa.Column('visible', sa.SmallInteger(), server_default='1', nullable=False, comment='是否可见:0隐藏,1显示'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除人ID'),
    sa.PrimaryKeyConstraint('id'),
    comment='权限/菜单表'
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=False)
    op.create_index(op.f('ix_permissions_parent_id'), 'permissions', ['parent_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('permission_id', sa.BigInteger(), nullable=False, comment='权限ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uk_role_permission'),
    comment='角色权限关联表'
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='角色编码'),
    sa.Column('sort', sa.SmallInteger(), server_default='0', nullable=False, comment='显示顺序'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='状态:0禁用,1正常'),
    sa.Column('data_scope', sa.SmallInteger(), server_default='1', nullable=False, comment='数据权限:1全部,2本部门及以下,3本部门,4仅本人'),
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除人ID'),
    sa.Column('tenant_id', sa.BigInteger(), server_default='0', nullable=False, comment='租户ID,0表示平台级'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色表'
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=False)
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='租户名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='租户编码'),
    sa.Column('contact_name', sa.String(length=50), nullable=True, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='状态:0禁用,1正常'),
    sa.Column('domain', sa.String(length=100), nullable=True, comment='绑定域名'),
    sa.Column('expire_time', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.Column('package_id', sa.BigInteger(), nullable=True, comment='套餐ID'),
    sa.Column('account_count', sa.Integer(), server_default='0', nullable=False, comment='账号数量'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除人ID'),
    sa.PrimaryKeyConstraint('id'),
    comment='租户表'
    )
    op.create_index(op.f('ix_tenants_code'), 'tenants', ['code'], unique=True)
    op.create_table('user_roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uk_user_role'),
    comment='用户角色关联表'
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_tenants_code'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_permissions_parent_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
