"""add menus table

Revision ID: 800c7f8c34e6
Revises: 51079b45a694
Create Date: 2025-12-07 15:40:42.976031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800c7f8c34e6'
down_revision: Union[str, None] = '51079b45a694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父菜单ID,NULL表示顶级菜单'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='菜单名称'),
    sa.Column('title', sa.String(length=50), nullable=False, comment='菜单标题(用于显示)'),
    sa.Column('path', sa.String(length=200), nullable=True, comment='路由路径'),
    sa.Column('component', sa.String(length=200), nullable=True, comment='组件路径'),
    sa.Column('redirect', sa.String(length=200), nullable=True, comment='重定向路径'),
    sa.Column('icon', sa.String(length=100), nullable=True, comment='图标'),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False, comment='排序(升序)'),
    sa.Column('type', sa.SmallInteger(), server_default='1', nullable=False, comment='类型:1目录,2菜单,3按钮'),
    sa.Column('permission_code', sa.String(length=100), nullable=True, comment='权限标识,如user:list'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='状态:0禁用,1启用'),
    sa.Column('visible', sa.SmallInteger(), server_default='1', nullable=False, comment='是否可见:0隐藏,1显示'),
    sa.Column('is_cache', sa.SmallInteger(), server_default='0', nullable=False, comment='是否缓存:0否,1是'),
    sa.Column('is_external', sa.SmallInteger(), server_default='0', nullable=False, comment='是否外链:0否,1是'),
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除人ID'),
    sa.Column('tenant_id', sa.BigInteger(), server_default='0', nullable=False, comment='租户ID,0表示平台级'),
    sa.PrimaryKeyConstraint('id'),
    comment='菜单表'
    )
    op.create_index(op.f('ix_menus_parent_id'), 'menus', ['parent_id'], unique=False)
    op.create_index(op.f('ix_menus_permission_code'), 'menus', ['permission_code'], unique=False)
    op.create_index(op.f('ix_menus_tenant_id'), 'menus', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menus_tenant_id'), table_name='menus')
    op.drop_index(op.f('ix_menus_permission_code'), table_name='menus')
    op.drop_index(op.f('ix_menus_parent_id'), table_name='menus')
    op.drop_table('menus')
    # ### end Alembic commands ###
