"""add log models

Revision ID: ca21df2d286f
Revises: 4ca356db0472
Create Date: 2025-12-07 18:17:40.704021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca21df2d286f'
down_revision: Union[str, None] = '4ca356db0472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_login_log',
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态:1成功,0失败'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='登录IP'),
    sa.Column('location', sa.String(length=100), nullable=True, comment='IP归属地'),
    sa.Column('browser', sa.String(length=100), nullable=True, comment='浏览器'),
    sa.Column('os', sa.String(length=100), nullable=True, comment='操作系统'),
    sa.Column('msg', sa.String(length=255), nullable=True, comment='提示消息'),
    sa.Column('login_time', sa.DateTime(), nullable=False, comment='登录时间'),
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除人ID'),
    sa.Column('tenant_id', sa.BigInteger(), server_default='0', nullable=False, comment='租户ID,0表示平台级'),
    sa.PrimaryKeyConstraint('id'),
    comment='登录日志表'
    )
    op.create_index(op.f('ix_sys_login_log_tenant_id'), 'sys_login_log', ['tenant_id'], unique=False)
    op.create_table('sys_opt_log',
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='用户名'),
    sa.Column('module', sa.String(length=50), nullable=True, comment='功能模块'),
    sa.Column('summary', sa.String(length=255), nullable=True, comment='操作摘要'),
    sa.Column('method', sa.String(length=20), nullable=True, comment='请求方法'),
    sa.Column('url', sa.String(length=255), nullable=True, comment='请求路径'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='请求IP'),
    sa.Column('location', sa.String(length=100), nullable=True, comment='IP归属地'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='UA系统'),
    sa.Column('params', sa.JSON(), nullable=True, comment='请求参数'),
    sa.Column('result', sa.JSON(), nullable=True, comment='响应结果'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态:1成功,0失败'),
    sa.Column('error_msg', sa.Text(), nullable=True, comment='错误消息'),
    sa.Column('duration', sa.Integer(), nullable=False, comment='耗时(ms)'),
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除人ID'),
    sa.Column('tenant_id', sa.BigInteger(), server_default='0', nullable=False, comment='租户ID,0表示平台级'),
    sa.PrimaryKeyConstraint('id'),
    comment='操作日志表'
    )
    op.create_index(op.f('ix_sys_opt_log_tenant_id'), 'sys_opt_log', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_opt_log_tenant_id'), table_name='sys_opt_log')
    op.drop_table('sys_opt_log')
    op.drop_index(op.f('ix_sys_login_log_tenant_id'), table_name='sys_login_log')
    op.drop_table('sys_login_log')
    # ### end Alembic commands ###
