"""add_tenant_id_and_audit_fields_to_associations

Revision ID: d675cfa187b4
Revises: ca21df2d286f
Create Date: 2025-12-07 18:42:00.717211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd675cfa187b4'
down_revision: Union[str, None] = 'ca21df2d286f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permissions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'))
    op.add_column('role_permissions', sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'))
    op.add_column('role_permissions', sa.Column('tenant_id', sa.BigInteger(), server_default='0', nullable=False, comment='租户ID,0表示平台级'))
    op.create_index(op.f('ix_role_permissions_tenant_id'), 'role_permissions', ['tenant_id'], unique=False)
    op.add_column('user_roles', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'))
    op.add_column('user_roles', sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'))
    op.add_column('user_roles', sa.Column('tenant_id', sa.BigInteger(), server_default='0', nullable=False, comment='租户ID,0表示平台级'))
    op.create_index(op.f('ix_user_roles_tenant_id'), 'user_roles', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles_tenant_id'), table_name='user_roles')
    op.drop_column('user_roles', 'tenant_id')
    op.drop_column('user_roles', 'created_by')
    op.drop_column('user_roles', 'created_at')
    op.drop_index(op.f('ix_role_permissions_tenant_id'), table_name='role_permissions')
    op.drop_column('role_permissions', 'tenant_id')
    op.drop_column('role_permissions', 'created_by')
    op.drop_column('role_permissions', 'created_at')
    # ### end Alembic commands ###
